version: '3.7'

services:
  database:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - "./mysql-database:/var/lib/mysql"
    networks:
      - symfony

  php8-sf6:
    build:
      context: ./
      dockerfile: php.dockerfile
    container_name: php8-sf6
    ports:
      - "9000:8000"
    volumes:
      - ./:/var/www/html
    networks:
      - symfony
    depends_on:
      - database

networks:
  symfony:
    driver: bridge
